"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['server.py']
DATA_FILES = ['brave_new_words.py', 'database.py', 'google_ngram.py', 'oed.py', 'pubmed.py', 'sfencyclopedia.py', 'sfEncyclopediaAcademia.txt', 'web_of_science.py', 'webscraper.py']
OPTIONS = {}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
